export const pagesRoutes = [
  ["v-8daa1a0e","/",{"title":"Unified Passwordless Platform"},["/index.html","/README.md"]],
  ["v-4bd12dfe","/add-custom-saml-app.html",{"title":"Add custom SAML app 📌"},["/add-custom-saml-app","/add-custom-saml-app.md"]],
  ["v-00dac4ea","/admin-controlled-user-recovery.html",{"title":"How to recover - user guide"},["/admin-controlled-user-recovery","/admin-controlled-user-recovery.md"]],
  ["v-74f221b6","/application-catalog.html",{"title":"Single Sign-On overview"},["/application-catalog","/application-catalog.md"]],
  ["v-23a5f41d","/application-entitlements.html",{"title":"Application entitlements 🔌"},["/application-entitlements","/application-entitlements.md"]],
  ["v-4fdf0f21","/cloud-radius-ip-address.html",{"title":"Cloud Radius IP address"},["/cloud-radius-ip-address","/cloud-radius-ip-address.md"]],
  ["v-3ee4b756","/cloud-radius-overview.html",{"title":"Cloud Radius overview"},["/cloud-radius-overview","/cloud-radius-overview.md"]],
  ["v-401b4678","/employee-onboarding.html",{"title":"Employee onboarding 🔑"},["/employee-onboarding","/employee-onboarding.md"]],
  ["v-1b5365cf","/group-management.html",{"title":"Group management"},["/group-management","/group-management.md"]],
  ["v-1faf83e3","/how-it-works.html",{"title":"How it works"},["/how-it-works","/how-it-works.md"]],
  ["v-7bff7bed","/how-to-obtain-saml-metadata-for-idemeum.html",{"title":"How to obtain SAML metadata for idemeum"},["/how-to-obtain-saml-metadata-for-idemeum","/how-to-obtain-saml-metadata-for-idemeum.md"]],
  ["v-424c9fad","/how-to-recover-device-user-guide.html",{"title":"How to recover - user guide"},["/how-to-recover-device-user-guide","/how-to-recover-device-user-guide.md"]],
  ["v-3d046675","/how-to-set-up-radius-integration.html",{"title":"How to set up Radius integration"},["/how-to-set-up-radius-integration","/how-to-set-up-radius-integration.md"]],
  ["v-f725a7c8","/integration-with-hr-system.html",{"title":"User source integration"},["/integration-with-hr-system","/integration-with-hr-system.md"]],
  ["v-52062726","/introduction.html",{"title":"Welcome to idemeum"},["/introduction","/introduction.md"]],
  ["v-7cf4753a","/lifecycle-management.html",{"title":"Automated account provisioning"},["/lifecycle-management","/lifecycle-management.md"]],
  ["v-427e2f43","/local-biometrics.html",{"title":"Local biometrics"},["/local-biometrics","/local-biometrics.md"]],
  ["v-9be1ec1c","/login-experience.html",{"title":"Login experience with MFA"},["/login-experience","/login-experience.md"]],
  ["v-673f9424","/mfa-organization-rollout.html",{"title":"MFA organization rollout 🏢"},["/mfa-organization-rollout","/mfa-organization-rollout.md"]],
  ["v-a11693fc","/mfa-overview.html",{"title":"Passwordless MFA overview 😄"},["/mfa-overview","/mfa-overview.md"]],
  ["v-3aa5727b","/mobile-app-security.html",{"title":"Security overview"},["/mobile-app-security","/mobile-app-security.md"]],
  ["v-30499639","/mobile-ui-overview.html",{"title":"Mobile UI overview"},["/mobile-ui-overview","/mobile-ui-overview.md"]],
  ["v-66e47bec","/password-vault-overview.html",{"title":"Password Vault overview"},["/password-vault-overview","/password-vault-overview.md"]],
  ["v-4ac023a2","/passwordless-mfa-desktop.html",{"title":"Passwordless MFA for desktop"},["/passwordless-mfa-desktop","/passwordless-mfa-desktop.md"]],
  ["v-707487ae","/passwordless-mfa-infra.html",{"title":"Passwordless MFA for infrastructure"},["/passwordless-mfa-infra","/passwordless-mfa-infra.md"]],
  ["v-3306300f","/passwordless-mfa-sso.html",{"title":"Passwordless MFA for Single Sign-On 🚤"},["/passwordless-mfa-sso","/passwordless-mfa-sso.md"]],
  ["v-49edf48c","/passwordless-mfa-vault.html",{"title":"Passwordless MFA for vault"},["/passwordless-mfa-vault","/passwordless-mfa-vault.md"]],
  ["v-9a49a6f4","/passwordless-mfa-vpn-wifi.html",{"title":"Passwordless MFA for Single Sign-On"},["/passwordless-mfa-vpn-wifi","/passwordless-mfa-vpn-wifi.md"]],
  ["v-33842ce2","/recovery-faq.html",{"title":"Recovery FAQ"},["/recovery-faq","/recovery-faq.md"]],
  ["v-13983dfe","/recovery-overview.html",{"title":"Recovery overview ❄️"},["/recovery-overview","/recovery-overview.md"]],
  ["v-25ecf9bc","/security-whitepaper.html",{"title":"Security white paper"},["/security-whitepaper","/security-whitepaper.md"]],
  ["v-64285c7e","/self-service-onboarding.html",{"title":"Try idemeum free"},["/self-service-onboarding","/self-service-onboarding.md"]],
  ["v-0aebaf02","/self-service-user-recovery.html",{"title":"Self service user recovery"},["/self-service-user-recovery","/self-service-user-recovery.md"]],
  ["v-72d50ce5","/remote-access/secure-remote-access-overview.html",{"title":"Secure Remote Access overview"},["/remote-access/secure-remote-access-overview","/remote-access/secure-remote-access-overview.md"]],
  ["v-3706649a","/404.html",{"title":""},["/404"]],
]
